# Search
search: 
  enable: true
  service: hexo # google/hexo/algolia/azure/baidu
  # google 
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:
  avatar:  /images/other.png

# friends link
links:
  - name: ClassicOldSong
    url: https://ccoooss.com
  - name: Frantic1048
    url: https://frantic1048.logdown.com/
  - name: Hclmaster
    url: https://hclmaster.github.io/
  - name: WANG Hsü-Tung
    url: https://whst.github.io/

# navigation menu
menu:
  - name: 主页
    slug: home
    url: /
  - name: 全部文章
    slug: archives
    url: /archives
  # - name: 所有分类
  #   slug: categories
  #   url:  /categories/ || th
  - name: 关于我们
    slug: about
    url: /about

# widgets
widgets:
  - about
  - biaoqia
  - categories
  - tagcloud

# Less
less:
  compress: true

# use url, not username
social:
- slug: github
  url: https://github.com/stkevintan
- slug: twitter
  url: https://twitter.com/kevinsfork
# - slug: rss
	# url: /atom.xml
